site_name: HTB Write-ups – Mohamed Trigui
theme:
  name: material
  palette:
    primary: indigo
    accent: teal

# Navigation sidebar
nav:
  - Home: 'index.md'
  - Sau: 'Sau/Sau.md'

# Plugins
plugins:
  - search
markdown_extensions:
  - toc:
      permalink: "🔗"

